#!/bin/bash
masukanTextDiAtas() {
    touch "$2" 2>/dev/null || true; printf "$1\n" | cat - "$2" > "$2.tmp" && mv "$2.tmp" "$2"
}

log() {
  # Log dengan warna
  log() {
    local COLOR_RESET="\033[0m"
    local COLOR_GREEN="\033[32m"
    local COLOR_YELLOW="\033[33m"
    local COLOR_RED="\033[31m"
    
    printf "${COLOR_GREEN}$(date +'%Y-%m-%d %H:%M:%S') [INFO]: $*${COLOR_RESET}\n"
  }
}

# Mendapatkan direktori kerja saat ini
log "Mendapatkan direktori kerja saat ini"
REPO_DIR="$(pwd)";
log "$REPO_DIR"

# git remote add origin https://github.com/Barqah-Xiex/brainxiex-bot-whatsapp.git;
log "git remote add origin https://github.com/Barqah-Xiex/brainxiex-bot-whatsapp.git;"
git remote set-url origin https://github.com/Barqah-Xiex/brainxiex-bot-whatsapp.git;

# Masuk ke direktori repository
log "Masuk ke direktori repository"
cd "$REPO_DIR" || { log "Direktori tidak ditemukan"; exit 1; }
log $(pwd)


log "Update Versi Project Dari: $(npm pkg get version)"
if [ $# -eq 0 ]; then
  npm version patch;
  argumen="Cuma Fix Beberapa Bug $(date +'%A %Y-%m-%d %H:%M:%S') v$(npm pkg get version | tr -d '"')"
else
  npm version minor;
  argumen="$* $(date +'%A %Y-%m-%d %H:%M:%S') v$(npm pkg get version | tr -d '"')"
fi
log "Menjadi: $(npm pkg get version)"

log "menambahkan ke changelog";
masukanTextDiAtas "[$(npm pkg get version | tr -d '"')] - $argumen\n\n" changelog.js

log "git remote";
git remote -v;

# Tarik perubahan dari remote repository
log "Tarik perubahan dari remote repository";
git pull origin main --rebase # Ganti 'main' dengan 'master' jika perlu

# Menambahkan semua perubahan
log "Menambahkan semua perubahan"
git add .

# Memeriksa status git
log "Memeriksa status git"
if [ "$(git status --porcelain)" ]; then
  # Jika ada perubahan, lakukan commit
  log Jika ada perubahan, lakukan commit
  git commit -m "$argumen"

  # Push ke remote repository
  log Push ke remote repository
  git push origin main # Ubah 'main' dengan 'master' jika branch utama Anda adalah master
  # npm publish --access public
else
  log "Tidak ada perubahan untuk di-commit."
fi
